### ISSUE TITLE
Enhancing Activity Popup

### ISSUE THREAD

**Issue by shriyakalakata** [software-students-spring2024/5-final-project-spring-2024-metty#39]
- [x] Allow clicking outside the popup to close the popup #42 
- [x] Take data from the database #41 
- [x] Allow only logged-in users only to view the graphs #41
- [x] Hovering over buttons darkens them - nav bar buttons and x buttons #42 
- [x] Style the stats section #43
- [x] Change the graph style #44 
- [x] Add an error message to non logged-in users #42 
- [x] Fix the order of days on the graph #44
- [x] Add headings to popup #44
